# Generated by Django 5.0.2 on 2024-02-28 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "metric_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("formula", models.JSONField(blank=True, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsumedUtxosFeatureMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockchain", models.CharField(max_length=255)),
                ("sub_chain", models.CharField(max_length=255)),
                ("sourceField", models.CharField(max_length=255)),
                ("targetField", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"unique_together": {("blockchain", "sub_chain", "sourceField")},},
        ),
        migrations.CreateModel(
            name="EmittedUtxosFeatureMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockchain", models.CharField(max_length=255)),
                ("sub_chain", models.CharField(max_length=255)),
                ("sourceField", models.CharField(max_length=255)),
                ("targetField", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"unique_together": {("blockchain", "sub_chain", "sourceField")},},
        ),
        migrations.CreateModel(
            name="TransactionsFeatureMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockchain", models.CharField(max_length=255)),
                ("sub_chain", models.CharField(max_length=255)),
                ("sourceField", models.CharField(max_length=255)),
                ("targetField", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"unique_together": {("blockchain", "sub_chain", "sourceField")},},
        ),
        migrations.CreateModel(
            name="BlockchainMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockchain_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("blockchain", models.CharField(max_length=255)),
                ("sub_chain", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="metrics.metric"
                    ),
                ),
            ],
            options={"unique_together": {("blockchain_id", "metric")},},
        ),
    ]
