class GeneralTransactionModel:
    def __init__(self, **kwargs):
        self.txHash = kwargs.get('txHash')
        self.blockHash = kwargs.get('blockHash')
        self.timestamp = kwargs.get('timestamp')
        self.blockHeight = kwargs.get('blockHeight')
        self.txType = kwargs.get('txType')
        self.memo = kwargs.get('memo')
        self.chainFormat = kwargs.get('chainFormat')
        self.amountUnlocked = kwargs.get('amountUnlocked')
        self.amountCreated = kwargs.get('amountCreated')
        self.sourceChain = kwargs.get('sourceChain')
        self.destinationChain = kwargs.get('destinationChain')
        self.rewardAddresses = kwargs.get('rewardAddresses')
        self.estimatedReward = kwargs.get('estimatedReward')
        self.startTimestamp = kwargs.get('startTimestamp')
        self.endTimestamp = kwargs.get('endTimestamp')
        self.delegationFeePercent = kwargs.get('delegationFeePercent')
        self.nodeId = kwargs.get('nodeId')
        self.subnetId = kwargs.get('subnetId')
        self.value = kwargs.get('value')
        self.amountStaked = kwargs.get('amountStaked')
        self.amountBurned = kwargs.get('amountBurned')

class GeneralUTXOModel():
    def __init__(self, **kwargs):
        self.utxoId = kwargs.get('utxoId')
        self.txHash = kwargs.get('txHash')
        self.txType = kwargs.get('txType')
        self.addresses = kwargs.get('addresses')
        self.value = kwargs.get('value')
        self.blockHash = kwargs.get('blockHash')
        self.assetId = kwargs.get('assetId')
        self.asset_name = kwargs.get('asset_name')
        self.asset_symbol = kwargs.get('symbol')
        self.denomination = kwargs.get('denomination')
        self.asset_type = kwargs.get('asset_type')
        self.amount = kwargs.get('amount')


class GeneralTransaction:
    def __init__(self, **kwargs):
        self.txHash = kwargs.get('txHash')
        self.blockHash = kwargs.get('blockHash')
        self.timestamp = kwargs.get('timestamp')
        self.blockHeight = kwargs.get('blockHeight')
        self.txType = kwargs.get('txType')
        self.memo = kwargs.get('memo')
        self.chainFormat = kwargs.get('chainFormat')
        self.amountUnlocked = kwargs.get('amountUnlocked')
        self.amountCreated = kwargs.get('amountCreated')
        self.sourceChain = kwargs.get('sourceChain')
        self.destinationChain = kwargs.get('destinationChain')
        self.rewardAddresses = kwargs.get('rewardAddresses')
        self.estimatedReward = kwargs.get('estimatedReward')
        self.startTimestamp = kwargs.get('startTimestamp')
        self.endTimestamp = kwargs.get('endTimestamp')
        self.delegationFeePercent = kwargs.get('delegationFeePercent')
        self.nodeId = kwargs.get('nodeId')
        self.subnetId = kwargs.get('subnetId')
        self.amountStaked = kwargs.get('amountStaked')
        self.amountBurned = kwargs.get('amountBurned')

        self.inputCount = kwargs.get('input_count')
        self.outputCount = kwargs.get('output_count')
        self.inputTotal = kwargs.get('input_total')
        self.inputTotalUSD = kwargs.get('input_total_usd')
        self.outputTotal = kwargs.get('output_total')
        self.outputTotalUSD = kwargs.get('output_total_usd')
        self.fee = kwargs.get('fee')
        self.feeUSD = kwargs.get('fee_usd')

        self.inputAddresses = kwargs.get('inputAddresses')
        self.outputAddresses = kwargs.get('outputAddresses')
        self.inputAmount = kwargs.get('inputAmount')
        self.outputAmount = kwargs.get('outputAmount')