# Generated by Django 4.1.3 on 2024-03-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blockchain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockchain", models.CharField(max_length=255, unique=True)),
                ("sub_chain", models.CharField(max_length=255)),
                ("original", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralModel",
            fields=[
                (
                    "field_name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("data_type", models.CharField(max_length=64)),
                ("description", models.TextField()),
            ],
            options={"db_table": "general_model",},
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "metric_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("grouping_type", models.CharField(max_length=255)),
                ("formula", models.JSONField(blank=True, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetricsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("blockchain", models.CharField(max_length=255)),
                ("subchain", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_data",
                        to="app.metric",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "blockchain", "subchain", "metric")},
            },
        ),
        migrations.CreateModel(
            name="ChainMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=255)),
                (
                    "blockchain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app.blockchain",
                    ),
                ),
            ],
            options={"unique_together": {("blockchain", "metric_name")},},
        ),
    ]
